# Generated by Django 5.1 on 2024-09-09 00:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_comment_count_video_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_thumbnail),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=api.models.upload_to_video),
        ),
    ]
